# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0002_auto_20180305_2058'),
        ('survey', '0008_auto_20180715_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('intro', models.CharField(blank=True, max_length=2000)),
                ('omschrijving', models.TextField()),
                ('locatie', models.CharField(blank=True, max_length=160)),
                ('start_datum', models.DateField()),
                ('einde_datum', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('aanmelding_formulier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aanmelding_rcd', to='survey.Survey')),
                ('evaluatie_formulier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluatie_rcd', to='survey.Survey')),
                ('programma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programma_rcd', to='conference.Conference')),
            ],
        ),
    ]
