# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='biography',
            field=models.TextField(blank=True, help_text='Uw korte introductie', verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(help_text='De naam zoals deze op het programma moet worden weergegeven.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Uw Twitter account', max_length=15),
        ),
    ]
