# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_auto_20180304_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='akkoordverklaring',
            field=models.BooleanField(default=False),
        ),
    ]
