# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-28 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afspraak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200, verbose_name='Onderwerp')),
                ('intro', models.CharField(blank=True, help_text='Geef korte toelichting op uitnodiging bericht.', max_length=2000)),
                ('duur', models.DurationField(blank=True, help_text='Invullen indien automatisch vooringevulde eindtijd gewenst is.', null=True)),
                ('aangemaakt', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Afspraken',
            },
        ),
        migrations.CreateModel(
            name='AfspraakDeelnemer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=40)),
                ('afspraak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afspraken.Afspraak')),
            ],
            options={
                'ordering': ['afspraak', 'deelnemer__naam'],
            },
        ),
        migrations.CreateModel(
            name='AfspraakOptie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('start', models.TimeField()),
                ('einde', models.TimeField(blank=True, null=True)),
                ('gekozen', models.BooleanField(default=False)),
                ('afspraak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afspraken.Afspraak')),
            ],
            options={
                'ordering': ['afspraak', 'datum', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Beschikbaar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('V', 'Ja'), ('?', 'Misschien'), ('X', 'Nee')], default='V', max_length=1)),
                ('afspraakoptie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afspraken.AfspraakOptie')),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afspraken.AfspraakDeelnemer')),
            ],
            options={
                'verbose_name_plural': 'Beschikbaar',
                'ordering': ['deelnemer', 'afspraakoptie'],
            },
        ),
        migrations.CreateModel(
            name='Deelnemer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_email', models.CharField(db_index=True, max_length=200, unique=True)),
                ('naam', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='afspraakdeelnemer',
            name='deelnemer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afspraken.Deelnemer'),
        ),
        migrations.AlterUniqueTogether(
            name='afspraakdeelnemer',
            unique_together=set([('afspraak', 'deelnemer')]),
        ),
    ]
