# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-29 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afspraken', '0002_pagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deelnemer',
            name='user',
        ),
    ]
