# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afspraken', '0003_remove_deelnemer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='afspraak',
            name='token',
            field=models.CharField(db_index=True, default='aaa', max_length=40),
            preserve_default=False,
        ),
    ]
