# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afspraken', '0005_afspraak_locatie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afspraakdeelnemer',
            options={'ordering': ['afspraak', 'naam']},
        ),
        migrations.AddField(
            model_name='afspraakdeelnemer',
            name='invite_email',
            field=models.CharField(default='aa.bb@cc.dd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afspraakdeelnemer',
            name='naam',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='afspraakdeelnemer',
            unique_together=set([('afspraak', 'invite_email')]),
        ),
        migrations.RemoveField(
            model_name='afspraakdeelnemer',
            name='deelnemer',
        ),
        migrations.DeleteModel(
            name='Deelnemer',
        ),
    ]
