#
# Copyright (C) 2014-2017 Ministerie van Infrastructuur en Milieu.
#
version: '3.3'

#
# Based on:
# https://docs.docker.com/compose/django/#create-a-django-project
# https://github.com/harikongu
#
services:

  vlabweb:
    image: sp-ontwikkel-docker-registry.external-cloud.nl:5000/bzk/ubr/vlab
    working_dir: /code
    environment:
      DATABASE_URL: postgres://django:geheim@vlabdatabase:5432/default
      DEBUG: "false"
      SECRET_KEY: QqSWs2y^F6APX6LU_2GkPPT^h;agI.v75BM_P|?mv2]v~6M-7asH#i%0HmkFt-.G=.+Z_:OJZbD9e~
      DJANGO_SETTINGS_MODULE: config.settings.development
      DJANGO_EMAIL_PORT: "8025"
      DJANGO_EMAIL_HOST: mailserver
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    networks:
      - apps
    #command: python3 manage.py migrate
    #command: ./entrypoint.sh
    entrypoint: /code/entrypoint.sh

  # Enable when using PostgreSQL:
  #
  vlabdatabase:
    image: postgres:alpine
    hostname: vlabdatabase
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: django
      POSTGRES_PASSWORD: geheim
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - vlab-data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    networks:
      - apps

  mailserver:
    image: sp-ontwikkel-docker-registry.external-cloud.nl:5000/ienm/sp/components/mail/exim:4.89-r5

    # Hostname as used in mail headers.
    # hostname: standaardplatform001.nl
    hostname: external-cloud.nl

    environment:
      # Connects to Mail Relay in SP-ontwikkel.
      - SMARTHOST=10.64.8.70::25
      #- SMTP_USERNAME=someuser
      #- SMTP_PASSWORD=password

    ports:
      - target: 8025
        published: 8025
        protocol: tcp
        mode: host
    networks:
      - apps
      
volumes:
  vlab-data:

networks:
  apps:
    external: true
