# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180515_2032'),
        ('pitchit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='formulier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitchit_formulier', to='survey.Survey'),
        ),
    ]
