# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen', '0008_pagecontent'),
        ('progkeuze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='Aanvinken als pagina getoond moet worden', verbose_name='Published')),
                ('need_logged_user', models.BooleanField()),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programmablokken', to='evenementen.Evenement')),
            ],
        ),
        migrations.RemoveField(
            model_name='programmablok',
            name='evenement',
        ),
        migrations.AddField(
            model_name='programmablok',
            name='programma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='progkeuze.Programma'),
            preserve_default=False,
        ),
    ]
