# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-20 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progkeuze', '0002_auto_20180820_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammaDeelnemer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_email', models.CharField(max_length=200)),
                ('naam', models.CharField(max_length=200)),
                ('token', models.CharField(db_index=True, max_length=40)),
                ('programma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progkeuze.Programma')),
            ],
            options={
                'ordering': ['programma', 'naam'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='evenementdeelnemer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='evenementdeelnemer',
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='programmakeuze',
            name='evenement',
        ),
        migrations.AddField(
            model_name='programmakeuze',
            name='programma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='progkeuze.Programma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programmakeuze',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progkeuze.ProgrammaDeelnemer'),
        ),
        migrations.DeleteModel(
            name='EvenementDeelnemer',
        ),
        migrations.AlterUniqueTogether(
            name='programmadeelnemer',
            unique_together=set([('programma', 'invite_email')]),
        ),
    ]
