# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progkeuze', '0003_auto_20180820_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmablok',
            name='programma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='progkeuze.Programma'),
        ),
    ]
