# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-30 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progkeuze', '0005_auto_20180822_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmablok',
            options={'ordering': ['programma', 'order']},
        ),
        migrations.AlterModelOptions(
            name='programmablokoptie',
            options={'ordering': ['programmablok', 'order']},
        ),
    ]
