# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-13 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_talkproposal_tutorialproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='abstract',
            field=models.TextField(help_text='Text wordt gepubliceerd.', verbose_name='Gedetailleerde beschrijving'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Interne notities. Text wordt niet gepubliceerd.', verbose_name='Notities'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='description',
            field=models.TextField(help_text='Text wordt gepubliceerd. Maximaal 400 karakters.', max_length=400, verbose_name='Samenvatting'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.ProposalKind', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='speakers.Speaker', verbose_name='Spreker'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Ingediend'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titel'),
        ),
    ]
