# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposalbase_akkoordverklaring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalbase',
            name='abstract',
            field=models.TextField(blank=True, help_text='Text wordt gepubliceerd.', verbose_name='Gedetailleerde beschrijving'),
        ),
        migrations.AlterField(
            model_name='proposalbase',
            name='description',
            field=models.TextField(blank=True, help_text='Text wordt gepubliceerd. Maximaal 400 karakters.', max_length=400, verbose_name='Samenvatting'),
        ),
    ]
