# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.CharField(blank=True, default='noreply@v-lab.ubrijk.nl', max_length=255, null=True)),
                ('from_email_name', models.CharField(blank=True, default='V-Lab team', max_length=255, null=True)),
                ('html_template', models.TextField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True, null=True)),
                ('is_text', models.BooleanField(default=False)),
                ('template_key', models.SlugField(help_text='Dit veld niet wijzigen omdat er naar wordt verwezen', unique=True)),
            ],
        ),
    ]
