# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='replyto_email',
            field=models.EmailField(blank=True, default='v-lab@rijksoverheid.nl', help_text='Algemene mailbox van de organisatie van het evenement', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email',
            field=models.EmailField(blank=True, default='noreply@v-lab.ubrijk.nl', help_text='Het email domein moet gelijk zijn aan de domeinnaam van de website', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email_name',
            field=models.EmailField(blank=True, default='V-Lab team', help_text='Naam van de organisatie van het evenement, dit wordt getoond als verzender van de email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_template',
            field=models.TextField(blank=True, default='{% extends "send_mail/emails/base.html" %}{% block content %}<h4>Geachte {{ voornaam }} {{ achternaam }},</h4>{% if survey.confirm %}<div>    <p>{{ survey.confirm|safe }}</p></div>{% endif %}<p>Ingevulde gegevens:</p><table>    <tbody>        {% for vraag in vragen %}        <tr>            <td>{{ vraag.vraag }}:</td>            <td>{{ vraag.antwoord }}</td>        </tr>        {% endfor %}    </tbody></table>{% endblock content %}{% block greeting %}<p>Met vriendelijke groet,    <br />    <br />V-Lab team</p>{% endblock greeting %}', help_text='HTML versie van de mail. Opmaak volgens https://docs.djangoproject.com/en/1.11/ref/templates/', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_text',
            field=models.BooleanField(default=False, help_text='Aanvinken als HTML versie niet gewenst is.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='plain_text',
            field=models.TextField(blank=True, default='{% load i18n %}{% autoescape off %}Geachte {{ voornaam }} {{ achternaam }},{% if survey.confirm %}{{ survey.confirm|striptags }}{% endif %}Ingevulde gegevens:{% for vraag in vragen %}{{ vraag.vraag }}: {{ vraag.antwoord }}{% endfor %}Met vriendelijke groet,V-Lab team{% endautoescape %}', help_text='Tekst versie van de mail voor email readers die geen HTML ondersteunen.', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, default='Bevestiging aanmelding: {{ evenement.naam }}', help_text='Mail onderwerp. Er kunnen variabelen worden gebruikt zoals bijvoorbeeld: {{ evenement.naam }}', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
