# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_auto_20181019_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='naam',
            field=models.CharField(default='V-Lab evenement aanmelding', max_length=200),
            preserve_default=False,
        ),
    ]
