# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.SlugField(unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('titel', models.CharField(max_length=64)),
                ('intro', models.CharField(blank=True, max_length=2000)),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
