# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20180305_2058'),
        ('survey', '0003_question_help_text'),
        ('evenementen', '0006_auto_20171022_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='evaluatie_formulier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluatie_evenement', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='programma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programma_evenement', to='conference.Conference'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='aanmelding_formulier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aanmelding_evenement', to='survey.Survey'),
        ),
    ]
