# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-04 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='akkoordverklaring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nieuwsbrief',
            field=models.BooleanField(default=False),
        ),
    ]
