# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-30 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180530_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='soort',
            field=models.CharField(default='Aanmelden', help_text='Formulier doel. Bijvoorbeeld: Aanmelden', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='avg_tekst1',
            field=models.CharField(help_text='Beschrijf hier bondig, eenvoudig en toegankelijk het primaire doel waarvoor u de persoonsgegevens vraagt, of de gegevens gedeeld worden en hoe lang ze bewaard worden.\nBijvoorbeeld:\nWij gebruiken uw gegevens om uw vraag te beantwoorden, waarna ze vernietigd worden. Uw informatie wordt niet met derden gedeeld.', max_length=1000, verbose_name='Informatie over de verwerking van uw persoonsgegevens'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='avg_tekst2',
            field=models.CharField(help_text='De doeleinden en rechtsgrond van de verwerking, en als u zich beroept op een gerechtvaardigd belang: op welk belang u zich beroept.\nIndien nodig: Of en waarom de betrokkene verplicht is de persoonsgegevens te verstrekken en wat de gevolgen zijn als de gegevens niet worden verstrekt.\nBijvoorbeeld:\nWij gebruiken uw gegevens, met uw toestemming, omdat wij anders niet in staat zijn om uw vraag te beantwoorden.', max_length=1000, verbose_name='Waarom worden deze gegevens gevraagd?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='avg_tekst3',
            field=models.CharField(help_text='Wat doet u met de gegevens en met wie worden ze gedeeld. Noem de ontvangers van de persoonsgegevens en, indien van toepassing, of u van plan bent de persoonsgegevens door te geven buiten de EU of een internationale organisatie en op welke juridische grond.\nBijvoorbeeld:\nWij gebruiken uw gegevens om uw vraag te beantwoorden. Uw vraag wordt door onze eigen medewerkers beantwoord. Uw gegevens worden niet met derden gedeeld.', max_length=1000, verbose_name='Op welke manier worden uw gegevens verwerkt?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='avg_tekst4',
            field=models.CharField(help_text='Laat hier weten wanneer de informatie wordt vernietigd. Houd hierbij rekening met wettelijke bewaartermijnen en de selectielijsten van uw organisatie.\nBijvoorbeeld:\nZodra wij uw vraag hebben beantwoord worden uw gegevens uit onze systemen verwijderd.', max_length=1000, verbose_name='Hoelang bewaren we uw gegevens?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(verbose_name='Omschrijving'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(help_text='Herkenbare naam om dit specifieke formulier te duiden', max_length=400, verbose_name='Naam'),
        ),
    ]
