# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180531_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='akkoordverklaring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(verbose_name='Toelichting'),
        ),
    ]
