# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20180531_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Tekstvak: veld voor langere tekst'), ('short-text', 'Tekstveld: veld voor 1 regel tekst'), ('radio', 'Keuzerondje: invuller kan 1 optie kiezen (‘ja/nee’)'), ('select', 'Keuzelijst: invuller maakt 1 keuze uit een uitklapmenu'), ('select-multiple', 'Aankruisvakje: invuller kan meer dan 1 optie aanvinken'), ('integer', 'Getal'), ('date', 'Datumveld (dd/mm/jjjj)'), ('likert', 'Likert-schaal: bijvoorbeeld keuze op schaal van 1 t/m 5')], default='text', max_length=200),
        ),
    ]
