# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
        ('survey', '0008_auto_20180715_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='confirm',
            field=models.TextField(blank=True, help_text='Deze tekst wordt opgenomen in de bevestigingsmail na het invullen van het formulier', null=True, verbose_name='Bevestiging tekst'),
        ),
        migrations.AddField(
            model_name='survey',
            name='emailTemplate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='send_mail.EmailTemplate'),
        ),
    ]
