# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180615_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='abstract',
            field=models.TextField(blank=True, help_text='Text wordt gepubliceerd.', verbose_name='Gedetailleerde beschrijving'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, help_text='Text wordt gepubliceerd. Maximaal 400 karakters.', verbose_name='Samenvatting'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titel'),
        ),
    ]
